export enum AppConstants {
  API_PREFIX = 'api',
  CACHE_TTL = 'CACHE_TTL_IN_MS',
  REDIS_HOST = 'REDIS_HOST',
  REDIS_PORT = 'REDIS_PORT',
  THROTTLER_TTL = 'THROTTLER_TTL_IN_MS',
  THROTTLER_LIMIT = 'THROTTLER_LIMIT',
  THROTTLER_STORE_URL = 'THROTTLER_STORE_URL',
  THROTTLER_ERROR_MESSAGE = 'Too many requests',
  LOG_LEVEL = 'LOG_LEVEL',
}
